04.---..---..-..-..-.   .-..-..-..-..-..-..-.
`| |'`| |' >  / | |__ | || .` || || | >  < 
 `-'  `-'  `-'  `----'`-'`-'`-'`----''-'`-`07

04ttylinux07 is distributed with ABSOLUTELY NO WARRANTY.
0bhttp://www.ttylinux.org07

09ttylinux boot options:07
 console=<ttyS*>09 ............... Use serial dev 07<ttyS*>09 for console login.07
 login=<ttyS*>[,<ttyS*>]09 ....... Include the listed serial devs for login.07
 nologin=<tty*>[,<tty*>]09 ....... Remove the listed serial devs from login.07
 modules=<module>[,<module>]09 ... Load specific kernel module(s) named 07<module>09.07
 enet09 .......................... Startup Ethernet networking.07
 nofirewall09 .................... Do not startup the firewall.07
 nofsck09 ........................ Do not check the file systems.07
 nosshd09 ........................ Do not run sshd, the Secure Shell server.07
 host=<name.domain.tld>09 ........ Set the hostname to 07<name.domain.tld>09.07
 tz=<timezone>09 ................. Set timezone to 07<timezone>09.07
 hwclock=(local|utc)09 ........... CMOS clock keeps local or UCT time.07

09Press <Enter> to begin or F2, F3 or F4 for boot options. To boot with one or07
09options, type "ttylinux" and the option(s) at the prompt.07

0f[F1-Main] [F2-Options] [F3-Options] [F4-Options]07
