-------------------------------------------------------------------------------

.---..---..-..-..-.   .-..-..-..-..-..-..-.
`| |'`| |' >  / | |__ | || .` || || | >  <
 `-'  `-'  `-'  `----'`-'`-'`-'`----''-'`-`

 ttylinux is distributed with ABSOLUTELY NO WARRANTY.
 http://www.ttylinux.org

ttylinux boot options:

 console=<ttyS*> ............... Use serial dev <ttyS*> for console login.
 login=<ttyS*>[,<ttyS*>] ....... Include the listed serial devs for login.
 nologin=<tty*>[,<tty*>] ....... Remove the listed serial devs from login.
 modules=<module>[,<module>] ... Load specific kernel module(s) named <module>.
 enet .......................... Startup Ethernet networking.
 nofirewall .................... Do not startup the firewall.
 nofsck ........................ Do not check the file systems.
 nosshd ........................ Do not run sshd, the Secure Shell server.
 host=<name.domain.tld> ........ Set the hostname to <name.domain.tld>.
 tz=<timezone> ................. Set timezone to <timezone>.
 hwclock=(local|utc) ........... CMOS clock keeps local or UCT time.

-------------------------------------------------------------------------------
