--- yaboot-1.3.13/Makefile	2004-07-11 13:12:03.000000000 -0700
+++ yaboot-1.3.13-new/Makefile	2010-03-27 09:44:24.000000000 -0700
@@ -1,3 +1,5 @@
+# 2010-03-27	drj	Added STRIP so as to support cross-compilation.
+
 ## Setup
 
 include Config
@@ -98,6 +100,7 @@
 LD		:= $(CROSS)ld
 AS		:= $(CROSS)as
 OBJCOPY		:= $(CROSS)objcopy
+STRIP		:= $(CROSS)strip
 
 lgcc = `$(CC) -print-libgcc-file-name`
 
@@ -172,10 +175,10 @@
 release: docs bindist clean
 
 strip: all
-	strip second/yaboot
-	strip --remove-section=.comment second/yaboot
-	strip util/addnote
-	strip --remove-section=.comment --remove-section=.note util/addnote
+	$(STRIP) second/yaboot
+	$(STRIP) --remove-section=.comment second/yaboot
+	$(STRIP) util/addnote
+	$(STRIP) --remove-section=.comment --remove-section=.note util/addnote
 
 install: all strip
 	install -d -o root -g root -m 0755 ${ROOT}/etc/
